[server]
maxUploadSize = 10

[theme]
primaryColor = "#FFD700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
# This hides the 'Hosted with Streamlit' footer/banner
hideToolbar = true 

# This new line hides the chat/help widget icon (the one circled in red)
hideSidebarNav = true
